// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePartInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	// RFC3339 datetime
	Deadline *string `json:"deadline"`
	// RFC3339 datetime
	CompletedAt *string `json:"completed_at"`
	ParentID    *string `json:"parent_id"`
}

type CreateUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Part struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	// RFC3339 datetime
	Deadline *string `json:"deadline"`
	// RFC3339 datetime
	CompletedAt *string `json:"completed_at"`
	ParentID    *string `json:"parent_id"`
}
